const String supabaseUrl = 'https://ivelkowygsgeutmxhdwd.supabase.co';
final String supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZWxrb3d5Z3NnZXV0bXhoZHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE5Mjk3MTQsImV4cCI6MjA0NzUwNTcxNH0.uhTMOy3LMlMRne5HUcGWgV1QKW7_goPrLSDMpLLLVv4';
const String yookassaShopId = '1098696';
const String yookassaSecretKey = 'test_bQe7hQdaq0OMZ0AOEEbiBAF8zocxYgUO6R56Bg69pfw';
