name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "CONFIRMATION_CODE=${{ secrets.CONFIRMATION_CODE }}" >> .env

      - name: Get dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build
        run: flutter build web --release --base-href "/gifthub/"

      - name: Copy build files to root
        run: |
          
          find . -maxdepth 1 ! -name '.git' ! -name '.github' -exec rm -rf {} +
          
          cp -r build/web/* .
          
          touch .nojekyll

      - name: Commit and push build
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Deploy web build"
          git push origin main