name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'


      - name: Show Flutter version
        run: |
          flutter --version
          dart --version

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build web (with detailed logging)
        run: flutter build web --release --base-href "/gifthub/" --verbose
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CONFIRMATION_CODE: ${{ secrets.CONFIRMATION_CODE }}

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
